// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f97acf5c-11ba-4f99-a8ca-d8025adee538",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JprK7MPLf",
    "aws_user_pools_web_client_id": "15jbprn1cedkbe9ie3td7rva3f",
};


export default awsmobile;
